# Generated by Django 5.2.11 on 2026-02-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentlog',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidentlog',
            name='new_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incidentlog',
            name='old_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
